// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Forecast2Uwp.Thunderstore.Data.Share;
//
//    var packRecentsResponse = PackRecentsResponse.FromJson(jsonString);

namespace Forecast2Uwp.Thunderstore.Data.Share
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class PackRecentsResponse
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("created-on")]
        public DateTimeOffset CreatedOn { get; set; }
    }

    public partial class PackRecentsResponse
    {
        public static PackRecentsResponse[] FromJson(string json) => JsonConvert.DeserializeObject<PackRecentsResponse[]>(json, Forecast2Uwp.Thunderstore.Data.Share.PackRecentsResponseConverter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this PackRecentsResponse[] self) => JsonConvert.SerializeObject(self, Forecast2Uwp.Thunderstore.Data.Share.PackRecentsResponseConverter.Settings);
    }

    internal static class PackRecentsResponseConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
